alias bye='sudo shutdown now' #shutdown system
alias c='clear' #clear terminal
alias gui='nautilus .' #opens gui file browser
alias update=~/update.sh
alias x='exit' #exits terminal
alias vimrc='vim ~/.vimrc' #open vimrc
#alias sl='ls' #fix my mistakes
alias cs='cd' #fix my mistakes
alias please='sudo $(history -p !!)' #run last command with elevated privileges if you ask nicely
alias intellij='/opt/idea-IU-163.11103.6/bin/idea.sh&' #launch intellij from terminal
alias CMake='cmake CMakeLists.txt' #quick cmake shortcut
alias resource='source ~/.bashrc' #re-source the bashrc and aliases
alias tensorflow='source ~/tensorflow/bin/activate' #activate tensorflow environment
alias python='python3'
alias bbb='ssh debian@129.123.28.138'
alias push=~/push.sh
alias untar='tar -xzvf'
