#!/bin/bash

cp ~/.vimrc ~/dotfiles
cp ~/.zshrc ~/dotfiles
cp ~/.i3/config ~/dotfiles/.i3
cp ~/.Xresources ~/dotfiles
cp ~/.Xdefaults ~/dotfiles
cp ~/.config/termite/config ~/dotfiles/.config/termite/

cd ~/dotfiles
git add .
git commit
~/sh/push.sh
