#!/bin/bash

NC='\033[0m' # No Color
BLUE='\033[0;34m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'

echo -e "${GREEN} COPYING FILES"
echo -e "${CYAN} VIM"
cp ~/.vimrc ~/dotfiles/.vimrc_vim
sleep .1

echo "ZSH"
cp ~/.zshrc ~/dotfiles/.zshrc_zsh
sleep .1

echo "i3"
cp ~/.i3/config ~/dotfiles/.config_i3
sleep .1

echo "URXVT"
cp ~/.Xresources ~/dotfiles/.Xresources_urxvt
sleep .1

echo "TERMITE"
cp ~/.config/termite/config ~/dotfiles/.config_termite
sleep .1

echo "TMUX"
cp ~/.tmux.conf ~/dotfiles/.tmux.conf
sleep .1

cd ~/dotfiles

echo -e "${BLUE} Adding to git"
sleep .1
git add .

echo -e "${BLUE} Committing to git ${NC}"
sleep .1
git commit

echo -e "${BLUE} Pushing to git ${NC}"
sleep .1
~/sh/push.sh

echo -e "${GREEN} [DONE] ${NC}"
