#!/bin/bash

cp ~/.vimrc ~/dotfiles/.vimrc_vim
cp ~/.zshrc ~/dotfiles/.zshrc_zsh
cp ~/.i3/config ~/dotfiles/.config_i3
cp ~/.Xresources ~/dotfiles/.Xresources_urxvt
cp ~/.config/termite/config ~/dotfiles/.config_termite

cd ~/dotfiles
git add .
git commit
~/sh/push.sh
